In [41]:
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential

In [42]:
x = pd.read_csv('/home/beuren/Documentos/LAMIA-Bootcamp/card-14/data/classificação binária/entradas_breast.csv')
y= pd.read_csv('/home/beuren/Documentos/LAMIA-Bootcamp/card-14/data/classificação binária/saidas_breast.csv')
# carregas os dados das features e a feature target

In [43]:
x_train, x_test,y_train,y_test = train_test_split(x,y,test_size=0.25)
# afz separação dos dados em teste e treino

In [44]:
(30 +1) /2
#faz o calculo para saber o numero ideal de neuronios na camada densa

15.5

In [64]:
rede_neural = Sequential([
    tf.keras.layers.InputLayer(shape=(30,)),
    # recebe uma tupla com o total de neuronios de entrada, 30 por onta das 30 features
    tf.keras.layers.Dense(units=16, activation='relu', kernel_initializer='random_uniform'),
    # define a quantidade de neuronios na camada densa com funcao de ativação relu
    tf.keras.layers.Dense(units=16, activation='relu', kernel_initializer='random_uniform'),
    # duas camadas ocultas na rede
    tf.keras.layers.Dense(units=1, activation='sigmoid')
    # escolhe a saida como 1 pois e uma classificação binaria entao usa somente uma saida com a funcao sigmoide para retornar a probabilidade
])

In [65]:
rede_neural.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_10 (Dense)                │ (None, 16)             │           496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 16)             │           272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_12 (Dense)                │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 785 (3.07 KB)

 Trainable params: 785 (3.07 KB)

 Non-trainable params: 0 (0.00 B)

In [66]:
otimizador = tf.keras.optimizers.Adam(learning_rate=0.001, clipvalue=0.5)

In [67]:
rede_neural.compile(optimizer=otimizador, loss= 'binary_crossentropy', metrics=['binary_accuracy'])
# parametros utilizados, o otimizador adam, o ajustados de pesos, e como medir os resultados do trein

In [68]:
rede_neural.fit(x_train,y_train, batch_size=10, epochs=100)
# treina o modelo com 100 registros por vez, e 100 vezes por todos os dados

Epoch 1/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - binary_accuracy: 0.5915 - loss: 0.7753
Epoch 2/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.6925 - loss: 0.5372
Epoch 3/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - binary_accuracy: 0.7653 - loss: 0.4661
Epoch 4/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - binary_accuracy: 0.7770 - loss: 0.5067
Epoch 5/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.7958 - loss: 0.6631
Epoch 6/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.7723 - loss: 0.5119
Epoch 7/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8099 - loss: 0.4601
Epoch 8/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8357 - loss: 0.4537
Epoch 9/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.8028 - loss: 0.4389
Epoch 10/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.8263 - loss: 0.4146
Epoch 11/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.8404 -

In [49]:
x_test

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave_points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave_points_worst,symmetry_worst,fractal_dimension_worst
30,18.63,25.11,124.80,1088.0,0.10640,0.18870,0.23190,0.124400,0.2183,0.06197,...,23.15,34.01,160.50,1670.0,0.1491,0.42570,0.61330,0.18480,0.3444,0.09782
404,12.34,14.95,78.29,469.1,0.08682,0.04571,0.02109,0.020540,0.1571,0.05708,...,13.18,16.85,84.11,533.1,0.1048,0.06744,0.04921,0.04793,0.2298,0.05974
227,15.00,15.51,97.45,684.5,0.08371,0.10960,0.06505,0.037800,0.1881,0.05907,...,16.41,19.31,114.20,808.2,0.1136,0.36270,0.34020,0.13790,0.2954,0.08362
410,11.36,17.57,72.49,399.8,0.08858,0.05313,0.02783,21.000000,0.1601,0.05913,...,13.05,36.32,85.07,521.3,0.1453,0.16220,0.18110,0.08698,0.2973,0.07745
244,19.40,23.50,129.10,1155.0,0.10270,0.15580,0.20490,0.088860,0.1978,0.06000,...,21.65,30.53,144.90,1417.0,0.1463,0.29680,0.34580,0.15640,292.0000,0.07614
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,19.45,19.33,126.50,1169.0,0.10350,0.11880,0.13790,0.085910,0.1776,0.05647,...,25.70,24.57,163.10,1972.0,0.1497,0.31610,0.43170,0.19990,0.3379,0.08950
57,14.71,21.59,95.55,656.9,0.11370,0.13650,0.12930,0.081230,0.2027,0.06758,...,17.87,30.70,115.70,985.5,0.1368,429.00000,0.35870,0.18340,0.3698,0.10940
546,10.32,16.35,65.31,324.9,0.09434,0.04994,0.01012,0.005495,0.1885,0.06201,...,11.25,21.77,71.12,384.9,0.1285,0.08842,0.04384,0.02381,0.2681,0.07399
68,9029.00,17.33,58.79,250.5,0.10660,0.14130,313.00000,0.043750,0.2111,0.08046,...,10.31,22.65,65.50,324.7,0.1482,0.43650,1252.00000,175.00000,0.4228,0.11750


In [ ]:
pesos0= rede_neural.layers[0].get_weights()
# mudança de pesos da camada de entrada 30 features
pesos0

[array([[ 3.70648541e-02,  1.22211404e-01, -2.55218565e-01,
         -3.69943172e-01, -8.28907862e-02, -8.46711174e-02,
          1.12902299e-01,  4.06689942e-02,  1.04275219e-01,
          9.02481601e-02, -2.94533968e-01, -2.10844465e-02,
         -7.52122840e-03, -1.02780238e-01,  1.02157809e-01,
         -1.32440627e-01],
        [ 1.36859238e-01,  1.63741913e-02, -1.90966189e-01,
         -2.74487436e-01, -8.91388282e-02, -1.48547545e-01,
         -5.23987822e-02,  2.05940768e-01,  2.06250772e-01,
          4.75719161e-02, -9.16185305e-02, -1.50166541e-01,
          1.04916543e-02, -1.06221355e-01, -1.47390617e-02,
         -1.45766303e-01],
        [ 1.11506306e-01,  2.59112921e-02, -1.68342680e-01,
         -4.31609759e-03,  3.12858187e-02, -7.37030879e-02,
         -1.84597466e-02,  1.31738961e-01,  1.66848972e-02,
          3.86200212e-02, -1.24938883e-01,  4.54960503e-02,
          2.92734802e-02, -1.04115598e-01,  1.50414824e-01,
         -7.08307102e-02],
        [ 3.7472978

In [ ]:
pesos1= rede_neural.layers[1].get_weights()
# mudança de pesos da primeira camada oculta
pesos1

[array([[-3.90933938e-02, -6.20831996e-02, -2.20105369e-02,
         -2.09090635e-02, -1.33232921e-01, -1.94349922e-02,
         -7.67910201e-03, -2.04830579e-02, -6.29473254e-02,
          2.18111739e-01, -9.19885859e-02, -1.94500268e-01,
         -2.00231984e-01, -2.89230287e-01, -1.67284742e-01,
         -4.66718301e-02],
        [-2.99111307e-02, -2.12597791e-02, -3.39068063e-02,
         -1.75206009e-02,  1.69604532e-02, -2.32468564e-02,
          3.02090924e-02, -8.94500315e-03, -1.04544751e-01,
         -2.03715488e-01, -9.86757204e-02,  1.41295686e-01,
          2.17306498e-03,  3.96895781e-02,  6.68034106e-02,
          6.20815977e-02],
        [-3.64085920e-02, -6.48454130e-02,  1.56610399e-01,
          2.03560721e-02, -2.72585824e-02,  3.98161225e-02,
         -2.67650019e-02, -6.88754767e-03,  2.61354093e-02,
          1.16668679e-01,  4.10663150e-02,  7.49806017e-02,
         -6.47885874e-02,  4.50543885e-05,  1.06037669e-02,
          1.16450280e-01],
        [-4.6074979

In [ ]:
pesos2= rede_neural.layers[2].get_weights()
# mudança de pesos da segunda camada oculta
pesos2

[array([[-0.11945869],
        [-0.12325674],
        [ 0.19976248],
        [ 0.27307498],
        [-0.30858588],
        [ 0.04509173],
        [-0.2807182 ],
        [-0.20600328],
        [-0.25348783],
        [ 0.32314742],
        [-0.3064359 ],
        [ 0.07628644],
        [ 0.03576559],
        [ 0.24363287],
        [-0.74752206],
        [-0.37781477]], dtype=float32),
 array([0.07582486], dtype=float32)]

In [73]:
len(pesos0)

2

In [69]:
previsoes = rede_neural.predict(x_test)
previsoes= previsoes >0.5
# faz a predicao com os dados de teste e coloca uma condição para numeros acima de 0.5 True e abaixo False

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step


In [53]:
previsoes

array([[False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

In [54]:
y_test

,0
30,0
404,1
227,1
410,1
244,0
...,...
254,0
57,0
546,1
68,1


In [56]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [70]:
accuracy_score(y_test, previsoes)
# compara os dados reais com as previsoes do modelo

0.8181818181818182

In [71]:
confusion_matrix(y_test, previsoes)

# matriz de confusao, 12 dados que eram benignos ele marcou como maligno e 2 malignos como benignos

array([[43, 16],
       [10, 74]])

In [ ]:
47 + 82, 12+2
# verificando as metricas da matriz

(129, 14)

In [62]:
129/143, 14/143

(0.9020979020979021, 0.0979020979020979)

In [ ]:
rede_neural.evaluate(x_test, y_test)
# confirmando a acuracia e o loss

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - binary_accuracy: 0.9021 - loss: 0.5570 


[0.5570301413536072, 0.9020978808403015]