In [1]:
import torch

In [ ]:
x=torch.tensor([[1,2,3],[4,5,6]])
# cria um tensor de duas dimensoes

In [ ]:
print(x.shape)
# mostrab sua dimensao

torch.Size([2, 3])


In [ ]:
x*10
# multiplica por 10

tensor([[10, 20, 30],
        [40, 50, 60]])

In [ ]:
x.add(10)
# soma 10 para cada numero dentro do tensorflow

tensor([[11, 12, 13],
        [14, 15, 16]])

In [6]:
x.view(3,2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
a = torch.ones((2,1,10))
# cria um tensor de 3 dimensoes preenchidos com 1
a

tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

In [ ]:
print(a.shape)
squeezed = a.squeeze(1)
# muda a dimensao do tensor removendo a dimensao 1
print(squeezed.shape)   

torch.Size([2, 1, 10])
torch.Size([2, 10])


In [11]:
a = torch.ones((2,2,10))
print(a.shape)
squeezed = a.squeeze(1)
print(squeezed.shape)
# nao muda a dimensao do tensor pois nao existe dimensao 1

torch.Size([2, 2, 10])
torch.Size([2, 2, 10])


In [12]:
a = torch.tensor([[1,2,3],[4,5,6]])
print(a.shape)
unsqueezed = a.unsqueeze(2)
print(unsqueezed.shape)

torch.Size([2, 3])
torch.Size([2, 3, 1])


In [13]:
a=torch.ones(2,3)

In [ ]:
print(a[None].shape)
print(a[:,None].shape)
print(a[:,:,None].shape)
# manipulação de indices para adicionar dimensões ao tensor

torch.Size([1, 2, 3])
torch.Size([2, 1, 3])
torch.Size([2, 3, 1])


# parte 2

In [22]:
x = torch.tensor([[1,2,3,4],[5,6,7,8]])
# cria uma matriz 2x2
y= torch.tensor([[1,2,3],
[2,3,4],
[4,5,6],
[7,8,9]])
# cria uma matriz de 4x3

In [23]:
torch.matmul(x,y)
# multiplica os dois tensors(matrizes) retornando uma matriz 2x3

tensor([[ 45,  55,  65],
        [101, 127, 153]])

In [24]:
x = torch.randn(2,3,2)
z=torch.cat((x,x),dim=1)
print(x.shape,z.shape)

torch.Size([2, 3, 2]) torch.Size([2, 6, 2])


In [ ]:
x = torch.randn(2,30,20)
z=torch.permute(x,(0,2,1))
# muda a ordem das dimensoes do tensor, nesse caso a dimensao 1 passa a ser 2 e a 2 passa a ser 1
print(x.shape,z.shape)

torch.Size([2, 30, 20]) torch.Size([2, 20, 30])
