In [ ]:
#!pip install ucimlrepo

In [ ]:
#!pip install scikeras==0.13.0 scikit-learn==1.5.2

In [3]:
from ucimlrepo import fetch_ucirepo
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras import utils as np_utils
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix
from scikeras.wrappers import KerasClassifier
from sklearn.model_selection import GridSearchCV

In [ ]:
wine = fetch_ucirepo(id=109 )
x = wine.data.features
y = wine.data.targets
# pega o dataset de qulidade de vinho no uci

In [5]:
x

,Alcohol,Malicacid,Ash,Alcalinity_of_ash,Magnesium,Total_phenols,Flavanoids,Nonflavanoid_phenols,Proanthocyanins,Color_intensity,Hue,0D280_0D315_of_diluted_wines,Proline
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
174,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
175,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
176,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840


In [ ]:
x.dtypes
# tipos dos dados

,0
Alcohol,float64
Malicacid,float64
Ash,float64
Alcalinity_of_ash,float64
Magnesium,int64
Total_phenols,float64
Flavanoids,float64
Nonflavanoid_phenols,float64
Proanthocyanins,float64
Color_intensity,float64


In [ ]:
x.isnull().sum()
# se tem null

,0
Alcohol,0
Malicacid,0
Ash,0
Alcalinity_of_ash,0
Magnesium,0
Total_phenols,0
Flavanoids,0
Nonflavanoid_phenols,0
Proanthocyanins,0
Color_intensity,0


In [8]:
y.values

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
    

In [ ]:
le = LabelEncoder()
y = le.fit_transform(y.values)
# transformo os valores strings em numeros
y

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [ ]:
y = np_utils.to_categorical(y)
# coloc em categorias
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [11]:
x.columns.value_counts().sum()

np.int64(13)

In [ ]:
def rede(neurons):
    rede = Sequential([
        tf.keras.layers.InputLayer(shape=(x.columns.value_counts().sum(),)),
        # 13 features na camada de entrada
        tf.keras.layers.Dense(units=neurons,activation='relu'),
        # primeira camada densa
        tf.keras.layers.Dense(units=neurons,activation='relu'),
        # segunda camada densa
        tf.keras.layers.Dense(units=3,activation='softmax'),
        # saida com 3 classes, softmax retorna a probabilidade de cada uma delas
    ])
    rede.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['categorical_accuracy'])
    return rede

In [13]:
rede = KerasClassifier(model = rede)

In [ ]:
params ={
    'batch_size':[10],
    'epochs':[200],
    'model__neurons': [8,10,12]
}# parametros testados

In [ ]:
gs = GridSearchCV(estimator=rede, param_grid=params,scoring='accuracy',cv=5)
# testa todos os paramtros, com cross validation de 5 para 5 partes do dataset

In [ ]:
gs = gs.fit(x,y)
# treina o modelo

Epoch 1/200
15/15 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - categorical_accuracy: 0.1620 - loss: 58.1516
Epoch 2/200
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - categorical_accuracy: 0.1620 - loss: 39.5439
Epoch 3/200
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - categorical_accuracy: 0.1901 - loss: 23.8373
Epoch 4/200
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - categorical_accuracy: 0.3732 - loss: 7.2094
Epoch 5/200
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - categorical_accuracy: 0.5915 - loss: 2.6548
Epoch 6/200
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - categorical_accuracy: 0.6056 - loss: 1.5370
Epoch 7/200
15/15 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - categorical_accuracy: 0.6338 - loss: 1.0671
Epoch 8/200
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - categorical_accuracy: 0.6408 - loss: 1.0205
Epoch 9/200
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - categorical_accuracy: 0.6197 - loss: 0.9864
Epoch 10/200
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - categorical_accuracy: 0.6338 - loss: 0.9593
Epoch 11/200
15/1

1/4 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step

A saída de streaming foi truncada nas últimas 5000 linhas.
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.7762 - loss: 0.4989 
Epoch 108/200
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.7552 - loss: 0.4690 
Epoch 109/200
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.7832 - loss: 0.4606 
Epoch 110/200
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.8322 - loss: 0.4146 
Epoch 111/200
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.7902 - loss: 0.4127 
Epoch 112/200
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.8112 - loss: 0.3983 
Epoch 113/200
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.7133 - loss: 0.5088 
Epoch 114/200
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.8042 - loss: 0.4493 
Epoch 115/200
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.7972 - loss: 0.4122 
Epoch 116/200
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - 

In [ ]:
acc=gs.best_score_
print(acc)
# melhor acuracia

0.9441269841269841


In [ ]:
gs.best_params_
# melhores paramtros

{'batch_size': 10, 'epochs': 200, 'model__neurons': 10}